---
- name: install prometheus on the system
  apt:
    name: prometheus
    state: present
    update_cache: yes

- name: Creates directory
  file: 
    path: "/data/prometheus/"
    state: directory
    mode: 0755

- name: config file
  template:
    src: templates/prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml

- name: alert config file
  copy:
    src: files/alertrules.yml
    dest: /etc/prometheus/alert.rules.yml

- name: Copy systemd init file
  template:
    src: templates/init.service.j2
    dest: /etc/systemd/system/prometheus.service
  notify: systemd_reload

- name: Start prometheus service
  service:
    name: prometheus
    state: started
    enabled: yes

- name: Check if prometheus is accessible
  uri:
    url: http://localhost:9090
    method: GET
    status_code: 200
