#!/bin/bash
/usr/bin/curl --user USERNAME:PASS http://jenkinsci/job/PROJECTNAME/build?token=buildtoken

#USERNAME is the username of jenkins server
#Password or authentication token of jenkins user, can be found in jenkins profile
#url for jenkins build job
#build job authentication token for remote execution, need to configured!