---
- name: Copy checkbox files for deployment
  copy: 
    src: deploy_checkbox.yml
    dest: /var/lib/jenkins/deploy_checkbox.yml

- name: Copy iTrust files for deployment
  copy: 
    src: deploy_itrust.yml
    dest: /var/lib/jenkins/deploy_itrust.yml

- name: Create folder
  file: 
    path: /.ssh
    state: directory

    
- name: Copy the key
  copy: 
    src: files/id_rsa   # Put your private key here
    dest: /.ssh/id_rsa
    mode: 0400

- name: email.properties
  copy:                                     
    src: templates/email.properties.j2
    dest: /var/lib/jenkins/email.properties
        

