---
- name: Create vars directory
  file:
    name: /var/lib/jenkins/vars
    state: directory

- name: Copy vars
  copy: 
    src: group_vars/all.yml
    dest: /var/lib/jenkins/vars/main.yml

- name: Copy checkbox files for deployment
  copy: 
    src: templates/deploy_checkbox.yml.j2
    dest: /var/lib/jenkins/deploy_checkbox.yml

- name: Copy iTrust files for deployment
  template: 
    src: templates/deploy_itrust.yml.j2
    dest: /var/lib/jenkins/deploy_itrust.yml

- name: Copy iTrust files for fuzzing
  template: 
    src: templates/deploy_itrust_fuzzer.yml.j2
    dest: /var/lib/jenkins/deploy_itrust_fuzzer.yml

- name: email.properties
  template:                                     
    src: templates/email.properties.j2
    dest: /var/lib/jenkins/email.properties
        
- name: Create rebuild directory
  file:
    name: job_rebuilds
    state: directory

- name: Copy Rebuild file for checkbox_job
  template:
    src: templates/rebuild_checkbox_job.yml.j2
    dest: "{{ vagrant_home }}/job_rebuilds/rebuild_checkbox_job.yml"


- name: Copy Rebuild file for itrust_job
  template:
    src: templates/rebuild_itrust_job.yml.j2
    dest: "{{ vagrant_home }}/job_rebuilds/rebuild_itrust_job.yml"

- name: Copy Build file for checkbox_job
  template:
    src: templates/build_checkbox_job.yml.j2
    dest: "{{ vagrant_home }}/job_rebuilds/build_checkbox_job.yml"

- name: Copy Build file for itrust_job
  template:
    src: templates/build_itrust.yml.j2
    dest: "{{ vagrant_home }}/job_rebuilds/build_itrust.yml"

- name: Copy Rebuild file for itrust_fuzzer_job
  template:
    src: templates/rebuild_itrust_fuzzer_job.yml.j2
    dest: "{{ vagrant_home }}/job_rebuilds/rebuild_itrust_fuzzer_job.yml"

# - name: Add Post commit hook
#   template:
#     src: templates/post_commit_hook.j2"
#     dest: "{{itrust_repo}}/iTrust2/.git/hooks/post-commit"
#     mode: 0767

# - name: Add Fuzzer.js file
#   copy:
#     src: files/fuzzer.js"
#     dest: "{{itrust_repo}}/iTrust2/fuzzer.js"
#     mode: 0666

# - name: adding package.json file for fuzzer.js
#   copy: 
#     src: files/package.json"
#     dest: "{{itrust_repo}}/iTrust2/package.json"
