---

- name: Copy Checkbox job
  copy:
    src: templates/checkbox_job.yml
    dest: jobs/checkbox_job.yml

- name: AWS Setup
  include: aws.yml
- pip:
    name: boto3

- name: See if Checkbox EC2 instance exists or not
  ec2_instance_facts:
    region: "us-east-1"
    filters:
     "tag:checkbox.io" : "{{checkbox}}"
  environment: 
    AWS_ACCESS_KEY_ID: "{{aws_access_key_id}}"
    AWS_SECRET_ACCESS_KEY: "{{aws_secret_access_key}}"
  register: ec2_checkboxio

  # - debug:
  #     var: ec2_checkboxio


- name: Create EC2 instance for checkbox.io
  shell: python main.py "{{checkbox}}"
  environment: 
    AWS_ACCESS_KEY_ID: "{{aws_access_key_id}}"
    AWS_SECRET_ACCESS_KEY: "{{aws_secret_access_key}}"
  when: ec2_checkboxio.instances | length==0

- name: Rights for pem file
  file:
    path: "{{checkbox}}.pem"
    mode: '400'

- name: Copy checkbox Job
  file:
    src: /ansible-srv/roles/create-jobs/templates/checkbox_job.yml
    dest: "{{ubuntu_home}}/jobs/checkbox_job.yml"

