---

- name: Install required packages
  apt: 
    name: ['python3','python3-pip']
    state: latest

- name: Install Python PIP
  tags: 'aws-cli'
  apt: >
    pkg=python-pip
    state=latest

- name: Install AWS CLI
  tags: 'aws-cli'
  pip: >
    name=awscli
    state=latest




- name: 'Create the AWS config directory'
  tags: 'aws-cli'
  become: 'yes'
  file: >
    path="{{ vagrant_home }}/.aws"
    state=directory
    mode=0755
    group={{ group }}
    owner={{ owner }}

- name: 'Copy AWS CLI credentials'
  tags: 'aws-cli'
  become: 'yes'
  template: >
    src=credentials.j2
    dest="{{ vagrant_home }}/.aws/credentials"
    mode=0600
    group={{ group }}
    owner={{ owner }}
  
- name: Sync the machine
  file:
    path: /etc/localtime 
    state: absent
    
- name: Sync the machine
  copy: 
    src: /usr/share/zoneinfo/America/New_York 
    dest: /etc/localtime



- pip:
    name: boto3


- name: See if EC2 instance exists or not
  ec2_instance_facts:
    aws_access_key: "{{aws_access_key_id}}"
    aws_secret_key: "{{aws_secret_access_key}}"
    region: "us-east-1"
    filters:
     "tag:jenkins" : "{{param}}"
     instance-state-name: running
  environment: 
    AWS_SECRET_ACCESS_KEY: "{{aws_secret_access_key}}"
    AWS_ACCESS_KEY_ID: "{{aws_access_key_id}}" 
    ANSIBLE_DISPLAY_ARGS_TO_STDOUT: 1
  register: ec2_instance


- name: Create Instance
  shell: python3 main.py {{param}}
  args:
    chdir: "/ansible-srv/roles/aws/templates/"
  environment: 
    AWS_ACCESS_KEY_ID: "{{aws_access_key_id}}"
    AWS_SECRET_ACCESS_KEY: "{{aws_secret_access_key}}"
  when: ec2_instance.instances | length==0

- name: AWS IP
  debug:
    var: ec2_instance.instances[0].public_ip_address


- name: Rights for pem file
  file:
    path: /ansible-srv/roles/aws/templates/{{param}}.pem
    mode: '400'

- name: Copy files
  copy:
    src: "/ansible-srv/roles/aws/templates/{{param}}.pem"
    dest: "/ansible-srv/{{param}}.pem"
    mode: '400'
  

- name: Sleep for some time
  shell: sleep 40s