---

- name: Install required packages
  apt: 
    name: ['python3','python3-pip']
    state: latest

- name: Install Python PIP
  tags: 'aws-cli'
  apt: >
    pkg=python-pip
    state=latest

- name: Install AWS CLI
  tags: 'aws-cli'
  pip: >
    name=awscli
    state=latest




- name: 'Create the AWS config directory'
  tags: 'aws-cli'
  become: 'yes'
  file: >
    path="{{ vagrant_home }}/.aws"
    state=directory
    mode=0755
    group={{ group }}
    owner={{ owner }}

- name: 'Copy AWS CLI credentials'
  tags: 'aws-cli'
  become: 'yes'
  template: >
    src=credentials.j2
    dest="{{ vagrant_home }}/.aws/credentials"
    mode=0600
    group={{ group }}
    owner={{ owner }}
  
- name: Sync the machine
  file:
    path: /etc/localtime 
    state: absent
    
- name: Sync the machine
  file: 
    src: /usr/share/zoneinfo/America/New_York 
    dest: /etc/localtime
    state: link

- name: Install requirements
  shell: pip install boto3
  args:
    chdir: "/ansible-srv/roles/aws/templates"



- name: Create Instance
  shell: python main.py
  args:
    chdir: "/ansible-srv/roles/aws/templates/"
  environment: 
    AWS_ACCESS_KEY_ID: "{{aws_access_key_id}}"
    AWS_SECRET_ACCESS_KEY: "{{aws_secret_access_key}}"



- name: Rights for pem file
  file:
    path: /ansible-srv/roles/aws/templates/aws-key.pem
    mode: '400'

- name: Copy files
  copy:
    src: "/ansible-srv/roles/aws/templates/aws-key.pem"
    dest: "/ansible-srv/aws-key.pem"
    mode: '400'
  

- name: Sleep for some time
  shell: sleep 40s