---
  # Install SQL and required packages
  - name: Install MySQL and required packages
    apt: 
      name: ['mysql-server', 'python3-dev', 'libmysqlclient-dev', 'python3-pip'] 
      state: present
      
  - name: Install Python package manager required for MySQL
    pip: name=mysqlclient
  
  # Set up root password for MySQL
  - name: Update MySQL root password 
    mysql_user: name=root host={{ item }} password={{ mysql_root_password }} state=present
    with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost

  - name: Copy root credentials .my.cnf file
    template:
      src: templates/root.cnf.j2
      dest: ~/.my.cnf

  
    
      
