- hosts: ec2instance
  become: yes
  vars_files:
    - variables.yml
  tasks:

    
   

    - name: Check if checkbox folder exists
      stat: 
        path: "{{ubuntu_home}}/checkbox.io"
      register: checkbox_exists

    - name: Delete folder if exists
      file:
        path: "{{ubuntu_home}}/checkbox.io"
        state: absent 
      when: checkbox_exists.stat.exists

    
    
    - name: get repo
      copy: 
        src: "{{ubuntu_home}}/checkbox.io"
        dest: "{{ubuntu_home}}"
        owner: "{{owner}}"
        group: "{{group}}"
      become_user: ubuntu

    

    - name: Dependencies
      command: npm install
      args:
        chdir: "{{ubuntu_home}}/checkbox.io/server-side/site"
      

    - name: Copy conf file 
      copy:
        src: "{{ubuntu_home}}/checkbox.io/local-conf/nginx.conf"
        dest: /etc/nginx/nginx.conf
        mode: 0644
        remote_src: yes
        owner: "{{owner}}"
        group: "{{group}}"

    - name: Replace the server root in the "default" file
      replace:
        dest: "{{ubuntu_home}}/checkbox.io/local-conf/default"
        regexp: "root (.)+;"
        replace: "root {{ubuntu_home}}/checkbox.io/public_html/;"

    - name: Copy default file 
      copy:
        src: "{{ubuntu_home}}/checkbox.io/local-conf/default"
        dest: /etc/nginx/sites-available/default
        mode: 0644
        remote_src: yes
        owner: "{{owner}}"
        group: "{{group}}"

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted 
    
    

    - name: stop
      shell: forever stopall
    

    - name: Start again
      shell: forever start server.js 
      args:
        chdir: "{{ubuntu_home}}/checkbox.io/server-side/site"
      environment:
        APP_PORT: 3002
        MONGO_PORT: 27017
        MONGO_IP: 127.0.0.1
        MONGO_USER: "{{mongo_checkbox_user}}"
        MONGO_PASSWORD: "{{mongo_admin_password}}"
        MAIL_USER: "{{email_username}}"
        MAIL_PASSWORD: "{{email_password}}"
        MAIL_SMTP: 'smtp.gmail.com'

    