- hosts: ec2instance
  become: yes
  vars_files:
    - variables.yml

  tasks:
    - name: db.properties
      copy:
        src: "{{jenkins_home}}/db.properties"
        dest: "{{ubuntu_home}}/iTrust2-v4/iTrust2/src/main/java/db.properties"
        remote_src: yes

    - name: email.properties
      copy:                                     
        src: "{{jenkins_home}}/email.properties"
        dest: "{{ubuntu_home}}/iTrust2-v4/iTrust2/src/main/java/email.properties"
        remote_src: yes
        

    - name: Edit mysql.conf file
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        line: skip-grant-tables
        insertafter: skip-external-locking

    - name: Restarting mysql service
      service:
        name: mysql
        state: restarted

    - name: mvn clean
      command: mvn clean 
      args:
        chdir: "{{ubuntu_home}/iTrust2-v4/iTrust2"

    - name: mvn test classes
      command: mvn process-test-classes
      args:
        chdir: "{{ubuntu_home}/iTrust2-v4/iTrust2"

    - name: Update apt
      apt: update_cache=yes


    - name: mvn jetty:run
      command: sh -c "mvn jetty:run &"
      args:
        chdir: "{{ubuntu_home}/iTrust2-v4/iTrust2"