- hosts: localhost
  become: yes
  vars_files:
    - variables.yml

  tasks:

    - name: Check if itrust folder exists
      stat: 
        path: "{{ubuntu_home}}/iTrust2-v4"
      register: itrust_exists

    - name: Delete folder if exists
      file:
        path: "{{ubuntu_home}}/iTrust2-v4"
        state: absent 
      when: itrust_exists.stat.exists


    - name: Clone repo
      command: 'git clone {{itrust_repo}}'
      args:
        chdir: "{{ubuntu_home}}"
      become_user: ubuntu

    - name: db.properties
      copy:
        src: "{{ubuntu_home}}/db.properties.j2"
        dest: "{{ubuntu_home}}/iTrust2-v4/iTrust2/src/main/java/db.properties"
        remote_src: yes

    - name: email.properties
      copy:                                     
        src: "{{ubuntu_home}}/email.properties.j2"
        dest: "{{ubuntu_home}}/iTrust2-v4/iTrust2/src/main/java/email.properties"
        remote_src: yes

    - name: copy hooks
      copy:                                     
        src: "{{ubuntu_home}}/post-commit"
        dest: "{{ubuntu_home}}/iTrust2-v4/.git/hooks/post-commit"
        mode: '+x'
        remote_src: yes
        

    - name: Edit mysql.conf file
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        line: skip-grant-tables
        insertafter: skip-external-locking

    - name: Restarting mysql service
      service:
        name: mysql
        state: restarted


    - name: mvn test classes
      command: mvn -f pom-data.xml process-test-classes
      args:
        chdir: "{{ubuntu_home}}/iTrust2-v4/iTrust2"

    - name: mvn clean
      command: mvn clean install
      args:
        chdir: "{{ubuntu_home}}/iTrust2-v4/iTrust2"

    
