- job:
    name: checkbox.io 2
    description: 'configure checkbox.io job'
    project-type: freestyle
    builders:
      - shell: 'sudo git clone {{ repo }}'
      - shell: 'cd /var/lib/jenkins/workspace/checkbox.io/checkbox.io/server-side/site && sudo npm install'
    