- scm:
    name: checkbox
    scm:
      - git:
         url: https://github.com/ShivamChamoli/checkbox.io.git
         branches:
          - origin/master

- job:
    name: checkbox.io 24
    description: 'configure checkbox.io job'
    project-type: freestyle
    properties:
      - github:
          url: https://github.com/ShivamChamoli/checkbox.io/
    builders:
      #- shell: 'sudo git clone https://github.com/ShivamChamoli/checkbox.io'
      #- shell: 'cd /var/lib/jenkins/workspace/checkbox.io/checkbox.io/server-side/site && sudo npm install'
      - shell: 'ansible-playbook /var/lib/jenkins/deploy_checkbox.yml'
    scm:
      - checkbox
    triggers:
      - pollscm:
          cron: ""
          ignore-post-commit-hooks: False

      
      
    