- job:
    name: iTrust
    description: 'configure iTrustjob'
    project-type: freestyle
    builders:
      #- shell: 'sudo git clone https://github.ncsu.edu/engr-csc326-staff/iTrust2-v4.git'
      - shell: 'ansible-playbook /var/lib/jenkins/deploy_itrust.yml'