- job:
    name: iTrust
    description: 'configure iTrustjob'
    project-type: freestyle
    builders:
      #- shell: 'sudo git clone https://github.ncsu.edu/engr-csc326-staff/iTrust2-v4.git'
      - shell: 'sudo cp -R /home/vagrant/iTrust2-v4 /var/lib/jenkins/jobs/iTrust/workspace/'
      - shell: 'sudo ansible-playbook /var/lib/jenkins/deploy_itrust_fuzzer.yml'
      - shell: 'cd /var/lib/jenkins/jobs/iTrust/workspace/iTrust2-v4/iTrust2 && sudo mvn clean'
      - shell: 'cd /var/lib/jenkins/jobs/iTrust/workspace/iTrust2-v4/iTrust2 && sudo mvn compile'
      #- shell: 'cd /var/lib/jenkins/jobs/iTrust/workspace/iTrust2-v4/iTrust2 && sudo mvn process-test-classes'
      - shell: 'cd /var/lib/jenkins/jobs/iTrust/workspace/iTrust2-v4/iTrust2 && sudo mvn checkstyle:checkstyle'      
      - shell: 'cd /var/lib/jenkins/jobs/iTrust/workspace/iTrust2-v4/iTrust2 && sudo mvn test site'
      #- shell: 'cd /var/lib/jenkins/jobs/iTrust/workspace/iTrust2-v4/iTrust2 && sudo mvn site'
      #- shell: 'sudo cp -R /home/vagrant/iTrust2-v4 /var/lib/jenkins/jobs/iTrust/workspace/'     
    publishers:
      - jacoco:
          exec-pattern: '**/target/coverage-reports/**.exec'
          targets:
            - instruction:
                unhealthy: 1
            - branch:
                unhealthy: 2
            - complexity:
                unhealthy: 3
            - line:
                unhealthy: 4
            - method:
                unhealthy: 5
            - class:
                unhealthy: 12
          