- job:
    name: checkbox.io
    description: 'build checkbox.io job'
    project-type: freestyle
    builders:
      #- shell: 'sudo git clone https://github.com/ShivamChamoli/checkbox.io'
      #- shell: 'cd /var/lib/jenkins/workspace/checkbox.io/checkbox.io/server-side/site && sudo npm install'
      - shell: 'ansible-playbook /var/lib/jenkins/deploy_checkbox.yml'    