---
- name: Create analysis directory
  file:
    name: analysis
    state: directory
  become: false
  
- name: Copy the package.json 
  template:
    src: templates/package.json
    dest: "{{vagrant_home}}/analysis/package.json"
  become: false

- name: Copy the analysis code
  template:
    src: templates/analysis.js.j2
    dest: "{{vagrant_home}}/analysis/analysis.js"
  become: false
  
- name: npm install the required packages
  command: npm install
  args:
    chdir: "{{vagrant_home}}/analysis/"
  become: true