---
- name: Create analysis directory
  file:
    name: analysis
    state: directory
  
- name: Copy the package.json onto the deployment server
  template:
    src: templates/package.json
    dest: {{vagrant_home}}/analysis/package.json

- name: Copy the analysis code-2 onto the deployment server
  template:
    src: templates/analysis.js.j2
    dest: {{vagrant_home}}/analysis/analysis.js

- name: npm install the required packages
  command: npm install
  args:
    chdir: {{vagrant_home}}/analysis/ 
  become: true

- include: create_checkbox_analysis_job.yml

- include: build_checkbox_analysis_job.yml