
---

- name: Security setup for configuration
  jenkins_script:
    script: |
        import jenkins.model.*
        import hudson.security.*
        def instance = Jenkins.getInstance()
        def strategy = new AuthorizationStrategy.Unsecured()
        instance.setAuthorizationStrategy(strategy)
        instance.save()
    user: admin
    url: "http://localhost:{{jenkins_port}}"
    password: "{{ adminpwd.stdout }}"

- name: build checkbox job
  shell: 'java -jar jenkins-cli.jar -s http://localhost:{{jenkins_port}}/ build checkbox.io'

- name: Increase security
  jenkins_script:
   script: |
    import jenkins.model.*
    import hudson.security.*
    def instance = Jenkins.getInstance()
    def hudsonRealm = new HudsonPrivateSecurityRealm(false)
    instance.setSecurityRealm(hudsonRealm)
    def strategy = new FullControlOnceLoggedInAuthorizationStrategy()
    strategy.setAllowAnonymousRead(false)
    instance.setAuthorizationStrategy(strategy)
    instance.save()
   user: admin
   url: "http://localhost:{{jenkins_port}}"
   password: "{{adminpwd.stdout}}"
