---
- hosts: ec2instance
  vars:
    ubuntu_home: '/home/ubuntu'
  become: true
  tasks:
    - name: Install microk8s
      command: snap install microk8s --classic
      
    - name: Wait for service to start
      shell: sleep 10s 

    - name: Check deployment status
      command: microk8s.kubectl get deployments 
      register: dep_status

    - name: Delete marqdown-app if it exists
      command: microk8s.kubectl delete deployments marqdown-app
      when:
        "'marqdown' in dep_status['stdout']"

    - name: Check service status
      command: microk8s.kubectl get svc 
      register: svc_status

    - name: Delete marqdown-service if it exists
      command: microk8s.kubectl delete service marqdown-service
      when:
        "'marqdown' in svc_status['stdout']"

    - name: Check deployment status
      command: microk8s.kubectl get deployments 
      register: dep_status
      retries: 6
      delay: 5
      until: >
        'marqdown' not in dep_status['stdout']
    
    - name: Copy the deployment file
      copy: 
        src: templates/deployment.yml
        dest: "{{ubuntu_home}}/deployment.yml"

    - name: Copy the service.yml for marqdown-service
      copy: 
        src: templates/service.yml
        dest: "{{ubuntu_home}}/service.yml"

    - name: Create a deployment for marqdown-app
      command: microk8s.kubectl create -f deployment.yml
      args:
        chdir: "{{ubuntu_home}}"

    - name: Start marqdown-app as a service
      command: microk8s.kubectl create -f service.yml
      args:
        chdir: "{{ubuntu_home}}"
