---
- name: install stress on the system
  apt:
    name: stress
    state: present
    update_cache: yes

# - name: Stress memory
#   become: true
#   shell: 'stress --cpu 8 --io 4 --vm 1 --vm-bytes 1024M --timeout 10s'