---
- hosts: all
  
  tasks:
  - name: install jre8
    apt:
     name: openjdk-8-jre
     state: present
     update_cache: yes
    

  - name: add jenkins repo key
    apt_key:
     url: https://pkg.jenkins.io/debian/jenkins.io.key
     state: present
    

  - name: add jenkins repo list file into sources.list.d
    apt_repository:
     repo: deb http://pkg.jenkins.io/debian-stable binary/
     state: present
    

  - name: install jenkins
    apt:
     name: jenkins
     state: present
     update_cache: yes
    

  - name: install git
    apt:
     name: git
     state: present
    