--- 
  - name: add jenkins repo key
    apt_key:
     url: https://pkg.jenkins.io/debian/jenkins.io.key
     state: present
    

  - name: add jenkins repo list file into sources.list.d
    apt_repository:
     repo: deb http://pkg.jenkins.io/debian-stable binary/
     state: present
    

  - name: install jenkins
    apt:
     name: jenkins
     state: present
     update_cache: yes
    

  - name: install git
    apt:
     name: git
     state: present

  - name: Add apt-repository for latest nodejs and npm
    shell: apt-add-repository "deb https://deb.nodesource.com/node_10.x $(lsb_release -sc) main"
    become: true

  - name: Re-install nodejs
    apt:
      name: nodejs
      state: latest
      update_cache: yes
      force: yes

  # - name: Install node
  #   apt:
  #     name: nodejs
  #     state: latest
  #     update_cache: yes
 
  # - name: Install npm
  #   apt:
  #     name: npm
  #     state: latest
  #     update_cache: yes

  - name: Change the Jenkins port
    template:
      src: templates/jenkins.j2
      dest: /etc/default/jenkins

  - name: restart service jenkins
    systemd:
      state: restarted
      daemon_reload: yes
      name: jenkins
    