---
- hosts: localhost
  become: yes
  vars_files: 
    variables.yml
  roles:
    #- python
    #- aws

- hosts: jenkins
  become: yes
  vars_files: 
    variables.yml
  roles:
    - ansible
    - maven
    - mysql
    - java
    - jenkins
    #- deployfiles
    #- job
    #- analysis
  