---
- hosts: localhost
  become: yes
  tasks:
    
    - name: Scan public key of github.ncsu.edu
      command: ssh-keyscan github.ncsu.edu
      register: github_key

    - name: Add public key of github.ncsu.edu to known_hosts file
      known_hosts:
        name: github.ncsu.edu
        key: '{{github_key.stdout}}'
        hash_host: no
        state: present

    - name: Git clone Ensure that private key /.ssh/id_rsa is present
      git:
        repo: 'git@github.ncsu.edu:engr-csc326-staff/iTrust2-v4.git'
        dest: iTrust2
        key_file: /.ssh/id_rsa        # Ensure that private key /.ssh/id_rsa is present


    - name: db.properties
      copy:
        src: /var/lib/jenkins/iTrust2/iTrust2/src/main/java/db.properties.template
        dest: /var/lib/jenkins/iTrust2/iTrust2/src/main/java/db.properties
        remote_src: yes

    - name: email.properties
      copy:                                     
        src: /var/lib/jenkins/email.properties
        dest: /var/lib/jenkins/iTrust2/iTrust2/src/main/java/email.properties
        remote_src: yes
        

    - name: Edit mysql.conf file
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        line: skip-grant-tables
        insertafter: skip-external-locking

    - name: Restarting mysql service
      service:
        name: mysql
        state: restarted
        
    - name: enabling access to mvn
      lineinfile:
        path: /etc/sudoers
        line: "jenkins ALL=(ALL) NOPASSWD: ALL"
    
    - name: mvn clean
      command: mvn clean 
      args:
        chdir: /var/lib/jenkins/iTrust2/iTrust2

    - name: mvn test classes
      command: mvn process-test-classes
      args:
        chdir: /var/lib/jenkins/iTrust2/iTrust2

    - name: Update apt
      apt: update_cache=yes


    - name: mvn jetty:run
      command: sh -c "mvn jetty:run &"
      args:
        chdir: /var/lib/jenkins/iTrust2/iTrust2