groups:
# - name: alert.rules
#   rules:
#   - alert: InstanceDown
#     expr: up == 0
#     for: 1m
#     labels:
#       severity: "critical"
#     annotations:
#       summary: "Endpoint {{ $labels.instance }} down"
#       description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minutes."
- name: alert.rules
  rules:
  - alert: high_cpu_load
    expr: node_load1 > 0.5
    for: 1s
    labels:
      severity: warning
    annotations:
      summary: "Server under high load"
      description: EC2 instance is under high load, the avg load 1m is at {{ $value}}. Reported by instance {{ $labels.instance }} of job {{ $labels.job }}."